url: https://github.com/kubernetes-sigs/windows-gmsa.git
subdirectory: charts/gmsa
commit: 7fb3451684ceaacdc1c1ce77c8101c1252d021e6
version: 3.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
