global:
  cattle:
    systemDefaultRegistry: ""

  kubectl:
    repository: rancher/kubectl
    tag: v1.24.17
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  # - name: "image-pull-secret"

nameOverride: ""

namespaceOverride: ""

image:
  repository: harrisonwaffel/ccg-plugin-installer # TODO: change to Rancher fork
  tag: latest # TODO: change to Rancher tag
  imagePullPolicy: Always # TODO: change to IfNotPresent

pause:
  # standard pause images do not work on host-process containers
  # TODO: create official pause images for host-process containers
  image:
    repository: oss/kubernetes/windows-host-process-containers-base-image
    tag: v1.0.0
    imagePullPolicy: IfNotPresent
  command:
  - "ping -t localhost > NULL"

nodeSelector: {}

affinity: {}

tolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

securityContext:
  windowsOptions:
    hostProcess: true
    runAsUserName: "NT AUTHORITY\\SYSTEM"
