#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

echo Starting validation

PACKAGES="$(go list ./...)"

if ! command -v golangci-lint; then
    if ! test ./bin/golangci-lint.exe; then
      echo Skipping validation: no golangci-lint available
      exit
    fi
fi

echo Running validation for "${OS}"
if [[ "${OS}" == "windows" ]]; then
     echo Running: golangci-lint.exe
    ./bin/golangci-lint.exe run
  else
    echo Running: golangci-lint
    golangci-lint run
fi

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
