name: Label issues
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        with:
          LABELS: "team/area2"
          NUMBER: ${{ github.event.issue.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
