name: Merge To Main CI

on:
  push:
    branches:
      - main

jobs:
  go-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.55
      - name: go-format
        run: test -z "$(go fmt ./... | tee /dev/stderr)"

  charts-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: validate-charts
        run: ./scripts/validate-charts

  linux-tests:
    needs: [go-validation, charts-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test-go
        run: ./scripts/test

  windows-tests:
    needs: [go-validation, charts-validation]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
      - name: test-go
        run: bash ./scripts/test

  chart-tests:
    needs: [go-validation, charts-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test-charts
        run: ./scripts/test-charts

  build-all-binaries:
    needs: [linux-tests, windows-tests, chart-tests]
    runs-on: windows-2022
    permissions:
      contents: read
      id-token: write
    env:
      REPO: ${{ vars.REPO }}
    steps:
      - name: retrieve dockerhub credentials
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: | 
            secret/data/github/repo/${{ github.repository }}/dockerhub/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/credentials password | DOCKER_PASSWORD
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
      - name: build-binaries
        run: bash ./scripts/build
      - name: package-binaries
        run: bash ./scripts/package
      - name: publish-containers
        run: bash ./scripts/publish
