name: PR Publish Comment
on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  stage-for-testing:
    # This job only runs for pull request comments
    # which contain only 'stage-for-testing'
    name: PR comment
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/stage-for-testing'
    runs-on: windows-2022
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Starting to stage this PR for testing'
            })
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'PR Has been staged for testing'
            })

